import type { TaskStep } from "../types/task";

// Shared rendering helpers for milestones (blocking reasons).
//
// A milestone marks the moment a blocking reason is released; the interval that
// ends at it is the time the task spent blocked on that reason. That interval is
// drawn as a fast-oscillating wavy line colored by the reason, so blocked spans
// stand out from the solid task bars. Reason colors are generated by the shared
// task color coder (see buildColorMapFromKeys) over the union of task types and
// blocking reasons, so they are globally distinct and consistent with the bars.

// wavyPath builds an SVG path for a fast wavy line from x0 to x1, oscillating
// around centerY. It is a chain of alternating half-period quadratic arcs, so it
// stays smooth while remaining compact. A small halfWave gives a high-frequency
// squiggle.
export function wavyPath(
  x0: number,
  x1: number,
  centerY: number,
  amplitude = 5,
  halfWave = 4,
): string {
  if (x1 - x0 <= 0) return "";

  let d = `M ${x0.toFixed(2)} ${centerY.toFixed(2)}`;
  let x = x0;
  let up = true;
  let guard = 0;
  while (x < x1 - 0.01 && guard < 6000) {
    const nx = Math.min(x + halfWave, x1);
    const cx = (x + nx) / 2;
    const cy = centerY + (up ? -amplitude : amplitude);
    d += ` Q ${cx.toFixed(2)} ${cy.toFixed(2)} ${nx.toFixed(2)} ${centerY.toFixed(2)}`;
    x = nx;
    up = !up;
    guard += 1;
  }
  return d;
}

// blockingKindAt returns the reason a task is blocked on at time t — the kind of
// the first milestone at or after t (the next one to be released). Mirrors the
// backend's findTaskBlockingKind. Returns "" when no milestone remains (the task
// is running, not blocked).
export function blockingKindAt(steps: TaskStep[] | null | undefined, t: number): string {
  let best = "";
  let bestTime = Infinity;
  for (const step of steps ?? []) {
    if (step.time >= t && step.time < bestTime) {
      bestTime = step.time;
      best = step.kind;
    }
  }
  return best;
}
