linters:
  enable-all: true
  disable:
    - varnamelen
    - nolintlint
    - testpackage
    - depguard
    - gochecknoglobals
    - paralleltest
    - nonamedreturns
    - dupword
    - recvcheck
    - ireturn
    - exhaustruct
    - gochecknoinits
    - godox
    - forcetypeassert
    - interfacebloat
    - exportloopref
    # Below are linters that we should consider enabling
    - dupl
    - forbidigo
    - errcheck
    - tagliatelle
    - err113
    - goconst
    - mnd
    - wrapcheck
    - sqlclosecheck
    - rowserrcheck
    - perfsprint
    - nlreturn
    - ginkgolinter
    - errorlint
    - unparam
    - copyloopvar
    - revive
    - wastedassign
    - staticcheck
    - predeclared
    - gocritic
    - godot
    - gofumpt
    - gosec
    - exhaustive
    - inamedparam
    - intrange
    - maintidx
    - predeclared
    - staticcheck
    - usestdlibvars
    - wastedassign
    - gci
    - nestif

linters-settings:
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 11
