version: "2"
run:
  concurrency: 4
  go: "1.20"
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - funlen
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - shadow
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - fmt:.*
        - io/ioutil:^Read.*
    funlen:
      lines: 60
      statements: 40
    gocyclo:
      min-complexity: 10
    govet:
      enable:
        - atomicalign
      disable:
        - shadow
    revive:
      confidence: 0.8
  exclusions:
    generated: lax
    paths:
      - .*\.my\.go$
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$