run:
  concurrency: 4
  timeout: 10m
  issues-exit-code: 1
  tests: true
  build-tags: []
  go: "1.20"

issues:
  exclude-files:
    - ".*\\.my\\.go$"
  exclude-dirs-use-default: true
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true
  enable:
    - revive
    - bodyclose
    - govet
    - stylecheck
    - funlen
    - gocyclo
    - lll
    - misspell
    - nakedret
    - prealloc
    - copyloopvar
    - unconvert
    - whitespace
    - gosimple
    - errcheck
    - ineffassign
    - unused
    - shadow
  fast: false

linters-settings:
  errcheck:
    exclude-functions:  # 改为数组格式
      - "fmt:.*"
      - "io/ioutil:^Read.*"
    check-type-assertions: false
    check-blank: false

  govet:
    enable:
      - atomicalign
    disable:
      - shadow

  funlen:
    lines: 60
    statements: 40

  gocyclo:
    min-complexity: 10

  revive:
    confidence: 0.8