// @ts-check
// First-party components sidebar as seen from `mem`. The current package is a
// category so its sub-packages nest under it; the other is a link.
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  componentsGroupSidebar: [
    {type: 'link', label: 'noc', href: '/packages/noc/'},
    {type: 'category', label: 'mem', collapsed: false, items: [{type: 'autogenerated', dirName: '.'}]},
  ],
};
export default sidebars;
