// @ts-check
// Core group sidebar as seen from the `messaging` package. Package names are
// top-level items in dependency order; the current package is the live entry.
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  coreGroupSidebar: [
    {type: 'link', label: 'hooking', href: '/packages/hooking/'},
    {type: 'link', label: 'naming', href: '/packages/naming/'},
    {type: 'link', label: 'timing', href: '/packages/timing/'},
    {type: 'link', label: 'queueing', href: '/packages/queueing/'},
    {type: 'link', label: 'datarecording', href: '/packages/datarecording/'},
    {type: 'autogenerated', dirName: '.'},
    {type: 'link', label: 'modeling', href: '/packages/modeling/'},
    {type: 'link', label: 'tracing', href: '/packages/tracing/'},
    {type: 'link', label: 'simulation', href: '/packages/simulation/'},
    {type: 'link', label: 'examples', href: '/packages/examples/'},
  ],
};
export default sidebars;
