// @ts-check
// Core group sidebar as seen from the `modeling` package. Package names are
// top-level items; the current package is the live entry, the rest are links.
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  coreGroupSidebar: [
    {type: 'autogenerated', dirName: '.'},
    {type: 'link', label: 'queueing', href: '/packages/queueing/'},
    {type: 'link', label: 'datarecording', href: '/packages/datarecording/'},
    {type: 'link', label: 'tracing', href: '/packages/tracing/'},
    {type: 'link', label: 'simulation', href: '/packages/simulation/'},
    {type: 'link', label: 'examples', href: '/packages/examples/'},
  ],
};
export default sidebars;
