// @ts-check
// First-party components sidebar as seen from `noc`. The current package is a
// category so its sub-packages nest under it; the other is a link.
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  componentsGroupSidebar: [
    {type: 'category', label: 'noc', collapsed: false, items: [{type: 'autogenerated', dirName: '.'}]},
    {type: 'link', label: 'mem', href: '/packages/mem/'},
  ],
};
export default sidebars;
