// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  coreGroupSidebar: [
    {type: 'link', label: 'modeling', href: '/packages/modeling/'},
    {type: 'autogenerated', dirName: '.'},
    {type: 'link', label: 'datarecording', href: '/packages/datarecording/'},
    {type: 'link', label: 'tracing', href: '/packages/tracing/'},
    {type: 'link', label: 'simulation', href: '/packages/simulation/'},
    {type: 'link', label: 'examples', href: '/packages/examples/'},
  ],
};
export default sidebars;
