// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sarchlab/akita/v4/noc/networking/arbitration (interfaces: Arbiter)
//
// Generated by this command:
//
//	mockgen -destination mock_arbitration_test.go -package switches -write_package_comment=false github.com/sarchlab/akita/v4/noc/networking/arbitration Arbiter
//

package switches

import (
	reflect "reflect"

	sim "github.com/sarchlab/akita/v4/sim"
	gomock "go.uber.org/mock/gomock"
)

// MockArbiter is a mock of Arbiter interface.
type MockArbiter struct {
	ctrl     *gomock.Controller
	recorder *MockArbiterMockRecorder
	isgomock struct{}
}

// MockArbiterMockRecorder is the mock recorder for MockArbiter.
type MockArbiterMockRecorder struct {
	mock *MockArbiter
}

// NewMockArbiter creates a new mock instance.
func NewMockArbiter(ctrl *gomock.Controller) *MockArbiter {
	mock := &MockArbiter{ctrl: ctrl}
	mock.recorder = &MockArbiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArbiter) EXPECT() *MockArbiterMockRecorder {
	return m.recorder
}

// AddBuffer mocks base method.
func (m *MockArbiter) AddBuffer(buf sim.Buffer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddBuffer", buf)
}

// AddBuffer indicates an expected call of AddBuffer.
func (mr *MockArbiterMockRecorder) AddBuffer(buf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBuffer", reflect.TypeOf((*MockArbiter)(nil).AddBuffer), buf)
}

// Arbitrate mocks base method.
func (m *MockArbiter) Arbitrate() []sim.Buffer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Arbitrate")
	ret0, _ := ret[0].([]sim.Buffer)
	return ret0
}

// Arbitrate indicates an expected call of Arbitrate.
func (mr *MockArbiterMockRecorder) Arbitrate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Arbitrate", reflect.TypeOf((*MockArbiter)(nil).Arbitrate))
}
