// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sarchlab/akita/v4/sim/model (interfaces: Port,Connection,Component)

package directconnection

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	hooking "github.com/sarchlab/akita/v4/sim/hooking"
	model "github.com/sarchlab/akita/v4/sim/model"
	timing "github.com/sarchlab/akita/v4/sim/timing"
)

// MockPort is a mock of Port interface.
type MockPort struct {
	ctrl     *gomock.Controller
	recorder *MockPortMockRecorder
}

// MockPortMockRecorder is the mock recorder for MockPort.
type MockPortMockRecorder struct {
	mock *MockPort
}

// NewMockPort creates a new mock instance.
func NewMockPort(ctrl *gomock.Controller) *MockPort {
	mock := &MockPort{ctrl: ctrl}
	mock.recorder = &MockPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPort) EXPECT() *MockPortMockRecorder {
	return m.recorder
}

// AcceptHook mocks base method.
func (m *MockPort) AcceptHook(arg0 hooking.Hook) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AcceptHook", arg0)
}

// AcceptHook indicates an expected call of AcceptHook.
func (mr *MockPortMockRecorder) AcceptHook(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptHook", reflect.TypeOf((*MockPort)(nil).AcceptHook), arg0)
}

// AsRemote mocks base method.
func (m *MockPort) AsRemote() model.RemotePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsRemote")
	ret0, _ := ret[0].(model.RemotePort)
	return ret0
}

// AsRemote indicates an expected call of AsRemote.
func (mr *MockPortMockRecorder) AsRemote() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsRemote", reflect.TypeOf((*MockPort)(nil).AsRemote))
}

// CanSend mocks base method.
func (m *MockPort) CanSend() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanSend")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanSend indicates an expected call of CanSend.
func (mr *MockPortMockRecorder) CanSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanSend", reflect.TypeOf((*MockPort)(nil).CanSend))
}

// Component mocks base method.
func (m *MockPort) Component() model.Component {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Component")
	ret0, _ := ret[0].(model.Component)
	return ret0
}

// Component indicates an expected call of Component.
func (mr *MockPortMockRecorder) Component() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Component", reflect.TypeOf((*MockPort)(nil).Component))
}

// Deliver mocks base method.
func (m *MockPort) Deliver(arg0 model.Msg) *model.SendError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deliver", arg0)
	ret0, _ := ret[0].(*model.SendError)
	return ret0
}

// Deliver indicates an expected call of Deliver.
func (mr *MockPortMockRecorder) Deliver(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deliver", reflect.TypeOf((*MockPort)(nil).Deliver), arg0)
}

// Hooks mocks base method.
func (m *MockPort) Hooks() []hooking.Hook {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hooks")
	ret0, _ := ret[0].([]hooking.Hook)
	return ret0
}

// Hooks indicates an expected call of Hooks.
func (mr *MockPortMockRecorder) Hooks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hooks", reflect.TypeOf((*MockPort)(nil).Hooks))
}

// Name mocks base method.
func (m *MockPort) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPortMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPort)(nil).Name))
}

// NotifyAvailable mocks base method.
func (m *MockPort) NotifyAvailable() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyAvailable")
}

// NotifyAvailable indicates an expected call of NotifyAvailable.
func (mr *MockPortMockRecorder) NotifyAvailable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyAvailable", reflect.TypeOf((*MockPort)(nil).NotifyAvailable))
}

// NumHooks mocks base method.
func (m *MockPort) NumHooks() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumHooks")
	ret0, _ := ret[0].(int)
	return ret0
}

// NumHooks indicates an expected call of NumHooks.
func (mr *MockPortMockRecorder) NumHooks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumHooks", reflect.TypeOf((*MockPort)(nil).NumHooks))
}

// PeekIncoming mocks base method.
func (m *MockPort) PeekIncoming() model.Msg {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PeekIncoming")
	ret0, _ := ret[0].(model.Msg)
	return ret0
}

// PeekIncoming indicates an expected call of PeekIncoming.
func (mr *MockPortMockRecorder) PeekIncoming() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PeekIncoming", reflect.TypeOf((*MockPort)(nil).PeekIncoming))
}

// PeekOutgoing mocks base method.
func (m *MockPort) PeekOutgoing() model.Msg {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PeekOutgoing")
	ret0, _ := ret[0].(model.Msg)
	return ret0
}

// PeekOutgoing indicates an expected call of PeekOutgoing.
func (mr *MockPortMockRecorder) PeekOutgoing() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PeekOutgoing", reflect.TypeOf((*MockPort)(nil).PeekOutgoing))
}

// RetrieveIncoming mocks base method.
func (m *MockPort) RetrieveIncoming() model.Msg {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveIncoming")
	ret0, _ := ret[0].(model.Msg)
	return ret0
}

// RetrieveIncoming indicates an expected call of RetrieveIncoming.
func (mr *MockPortMockRecorder) RetrieveIncoming() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveIncoming", reflect.TypeOf((*MockPort)(nil).RetrieveIncoming))
}

// RetrieveOutgoing mocks base method.
func (m *MockPort) RetrieveOutgoing() model.Msg {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveOutgoing")
	ret0, _ := ret[0].(model.Msg)
	return ret0
}

// RetrieveOutgoing indicates an expected call of RetrieveOutgoing.
func (mr *MockPortMockRecorder) RetrieveOutgoing() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveOutgoing", reflect.TypeOf((*MockPort)(nil).RetrieveOutgoing))
}

// Send mocks base method.
func (m *MockPort) Send(arg0 model.Msg) *model.SendError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(*model.SendError)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockPortMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockPort)(nil).Send), arg0)
}

// SetConnection mocks base method.
func (m *MockPort) SetConnection(arg0 model.Connection) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetConnection", arg0)
}

// SetConnection indicates an expected call of SetConnection.
func (mr *MockPortMockRecorder) SetConnection(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConnection", reflect.TypeOf((*MockPort)(nil).SetConnection), arg0)
}

// MockConnection is a mock of Connection interface.
type MockConnection struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionMockRecorder
}

// MockConnectionMockRecorder is the mock recorder for MockConnection.
type MockConnectionMockRecorder struct {
	mock *MockConnection
}

// NewMockConnection creates a new mock instance.
func NewMockConnection(ctrl *gomock.Controller) *MockConnection {
	mock := &MockConnection{ctrl: ctrl}
	mock.recorder = &MockConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnection) EXPECT() *MockConnectionMockRecorder {
	return m.recorder
}

// AcceptHook mocks base method.
func (m *MockConnection) AcceptHook(arg0 hooking.Hook) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AcceptHook", arg0)
}

// AcceptHook indicates an expected call of AcceptHook.
func (mr *MockConnectionMockRecorder) AcceptHook(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptHook", reflect.TypeOf((*MockConnection)(nil).AcceptHook), arg0)
}

// Hooks mocks base method.
func (m *MockConnection) Hooks() []hooking.Hook {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hooks")
	ret0, _ := ret[0].([]hooking.Hook)
	return ret0
}

// Hooks indicates an expected call of Hooks.
func (mr *MockConnectionMockRecorder) Hooks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hooks", reflect.TypeOf((*MockConnection)(nil).Hooks))
}

// Name mocks base method.
func (m *MockConnection) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockConnectionMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockConnection)(nil).Name))
}

// NotifyAvailable mocks base method.
func (m *MockConnection) NotifyAvailable(arg0 model.Port) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyAvailable", arg0)
}

// NotifyAvailable indicates an expected call of NotifyAvailable.
func (mr *MockConnectionMockRecorder) NotifyAvailable(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyAvailable", reflect.TypeOf((*MockConnection)(nil).NotifyAvailable), arg0)
}

// NotifySend mocks base method.
func (m *MockConnection) NotifySend() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifySend")
}

// NotifySend indicates an expected call of NotifySend.
func (mr *MockConnectionMockRecorder) NotifySend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifySend", reflect.TypeOf((*MockConnection)(nil).NotifySend))
}

// NumHooks mocks base method.
func (m *MockConnection) NumHooks() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumHooks")
	ret0, _ := ret[0].(int)
	return ret0
}

// NumHooks indicates an expected call of NumHooks.
func (mr *MockConnectionMockRecorder) NumHooks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumHooks", reflect.TypeOf((*MockConnection)(nil).NumHooks))
}

// PlugIn mocks base method.
func (m *MockConnection) PlugIn(arg0 model.Port) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PlugIn", arg0)
}

// PlugIn indicates an expected call of PlugIn.
func (mr *MockConnectionMockRecorder) PlugIn(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlugIn", reflect.TypeOf((*MockConnection)(nil).PlugIn), arg0)
}

// Unplug mocks base method.
func (m *MockConnection) Unplug(arg0 model.Port) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unplug", arg0)
}

// Unplug indicates an expected call of Unplug.
func (mr *MockConnectionMockRecorder) Unplug(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unplug", reflect.TypeOf((*MockConnection)(nil).Unplug), arg0)
}

// MockComponent is a mock of Component interface.
type MockComponent struct {
	ctrl     *gomock.Controller
	recorder *MockComponentMockRecorder
}

// MockComponentMockRecorder is the mock recorder for MockComponent.
type MockComponentMockRecorder struct {
	mock *MockComponent
}

// NewMockComponent creates a new mock instance.
func NewMockComponent(ctrl *gomock.Controller) *MockComponent {
	mock := &MockComponent{ctrl: ctrl}
	mock.recorder = &MockComponentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComponent) EXPECT() *MockComponentMockRecorder {
	return m.recorder
}

// AcceptHook mocks base method.
func (m *MockComponent) AcceptHook(arg0 hooking.Hook) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AcceptHook", arg0)
}

// AcceptHook indicates an expected call of AcceptHook.
func (mr *MockComponentMockRecorder) AcceptHook(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptHook", reflect.TypeOf((*MockComponent)(nil).AcceptHook), arg0)
}

// AddPort mocks base method.
func (m *MockComponent) AddPort(arg0 string, arg1 model.Port) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddPort", arg0, arg1)
}

// AddPort indicates an expected call of AddPort.
func (mr *MockComponentMockRecorder) AddPort(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPort", reflect.TypeOf((*MockComponent)(nil).AddPort), arg0, arg1)
}

// GetPortByName mocks base method.
func (m *MockComponent) GetPortByName(arg0 string) model.Port {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPortByName", arg0)
	ret0, _ := ret[0].(model.Port)
	return ret0
}

// GetPortByName indicates an expected call of GetPortByName.
func (mr *MockComponentMockRecorder) GetPortByName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPortByName", reflect.TypeOf((*MockComponent)(nil).GetPortByName), arg0)
}

// Handle mocks base method.
func (m *MockComponent) Handle(arg0 timing.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockComponentMockRecorder) Handle(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockComponent)(nil).Handle), arg0)
}

// Hooks mocks base method.
func (m *MockComponent) Hooks() []hooking.Hook {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hooks")
	ret0, _ := ret[0].([]hooking.Hook)
	return ret0
}

// Hooks indicates an expected call of Hooks.
func (mr *MockComponentMockRecorder) Hooks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hooks", reflect.TypeOf((*MockComponent)(nil).Hooks))
}

// Name mocks base method.
func (m *MockComponent) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockComponentMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockComponent)(nil).Name))
}

// NotifyPortFree mocks base method.
func (m *MockComponent) NotifyPortFree(arg0 model.Port) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyPortFree", arg0)
}

// NotifyPortFree indicates an expected call of NotifyPortFree.
func (mr *MockComponentMockRecorder) NotifyPortFree(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyPortFree", reflect.TypeOf((*MockComponent)(nil).NotifyPortFree), arg0)
}

// NotifyRecv mocks base method.
func (m *MockComponent) NotifyRecv(arg0 model.Port) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyRecv", arg0)
}

// NotifyRecv indicates an expected call of NotifyRecv.
func (mr *MockComponentMockRecorder) NotifyRecv(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyRecv", reflect.TypeOf((*MockComponent)(nil).NotifyRecv), arg0)
}

// NumHooks mocks base method.
func (m *MockComponent) NumHooks() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumHooks")
	ret0, _ := ret[0].(int)
	return ret0
}

// NumHooks indicates an expected call of NumHooks.
func (mr *MockComponentMockRecorder) NumHooks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumHooks", reflect.TypeOf((*MockComponent)(nil).NumHooks))
}

// Ports mocks base method.
func (m *MockComponent) Ports() []model.Port {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ports")
	ret0, _ := ret[0].([]model.Port)
	return ret0
}

// Ports indicates an expected call of Ports.
func (mr *MockComponentMockRecorder) Ports() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ports", reflect.TypeOf((*MockComponent)(nil).Ports))
}
