// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sarchlab/akita/v5/noc/networking/arbitration (interfaces: FlitBuffer)
//
// Generated by this command:
//
//	mockgen -destination mock_queueing_test.go -package arbitration -write_package_comment=false github.com/sarchlab/akita/v5/noc/networking/arbitration FlitBuffer
//

package arbitration

import (
	reflect "reflect"

	messaging "github.com/sarchlab/akita/v5/noc/messaging"
	sim "github.com/sarchlab/akita/v5/sim"
	gomock "go.uber.org/mock/gomock"
)

// MockFlitBuffer is a mock of FlitBuffer interface.
type MockFlitBuffer struct {
	ctrl     *gomock.Controller
	recorder *MockFlitBufferMockRecorder
	isgomock struct{}
}

// MockFlitBufferMockRecorder is the mock recorder for MockFlitBuffer.
type MockFlitBufferMockRecorder struct {
	mock *MockFlitBuffer
}

// NewMockFlitBuffer creates a new mock instance.
func NewMockFlitBuffer(ctrl *gomock.Controller) *MockFlitBuffer {
	mock := &MockFlitBuffer{ctrl: ctrl}
	mock.recorder = &MockFlitBufferMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlitBuffer) EXPECT() *MockFlitBufferMockRecorder {
	return m.recorder
}

// AcceptHook mocks base method.
func (m *MockFlitBuffer) AcceptHook(hook sim.Hook) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AcceptHook", hook)
}

// AcceptHook indicates an expected call of AcceptHook.
func (mr *MockFlitBufferMockRecorder) AcceptHook(hook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptHook", reflect.TypeOf((*MockFlitBuffer)(nil).AcceptHook), hook)
}

// CanPush mocks base method.
func (m *MockFlitBuffer) CanPush() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanPush")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanPush indicates an expected call of CanPush.
func (mr *MockFlitBufferMockRecorder) CanPush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanPush", reflect.TypeOf((*MockFlitBuffer)(nil).CanPush))
}

// Capacity mocks base method.
func (m *MockFlitBuffer) Capacity() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Capacity")
	ret0, _ := ret[0].(int)
	return ret0
}

// Capacity indicates an expected call of Capacity.
func (mr *MockFlitBufferMockRecorder) Capacity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Capacity", reflect.TypeOf((*MockFlitBuffer)(nil).Capacity))
}

// Hooks mocks base method.
func (m *MockFlitBuffer) Hooks() []sim.Hook {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hooks")
	ret0, _ := ret[0].([]sim.Hook)
	return ret0
}

// Hooks indicates an expected call of Hooks.
func (mr *MockFlitBufferMockRecorder) Hooks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hooks", reflect.TypeOf((*MockFlitBuffer)(nil).Hooks))
}

// Name mocks base method.
func (m *MockFlitBuffer) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockFlitBufferMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockFlitBuffer)(nil).Name))
}

// NumHooks mocks base method.
func (m *MockFlitBuffer) NumHooks() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumHooks")
	ret0, _ := ret[0].(int)
	return ret0
}

// NumHooks indicates an expected call of NumHooks.
func (mr *MockFlitBufferMockRecorder) NumHooks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumHooks", reflect.TypeOf((*MockFlitBuffer)(nil).NumHooks))
}

// PeekFlit mocks base method.
func (m *MockFlitBuffer) PeekFlit() *messaging.Flit {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PeekFlit")
	ret0, _ := ret[0].(*messaging.Flit)
	return ret0
}

// PeekFlit indicates an expected call of PeekFlit.
func (mr *MockFlitBufferMockRecorder) PeekFlit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PeekFlit", reflect.TypeOf((*MockFlitBuffer)(nil).PeekFlit))
}

// Size mocks base method.
func (m *MockFlitBuffer) Size() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size.
func (mr *MockFlitBufferMockRecorder) Size() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockFlitBuffer)(nil).Size))
}
