package endpoint

import (
	"math"

	"github.com/sarchlab/akita/v5/modeling"
	"github.com/sarchlab/akita/v5/noc/packetization"

	"github.com/sarchlab/akita/v5/timing"
	"github.com/sarchlab/akita/v5/tracing"

	// msgMetaToFlits converts a MsgMeta into a slice of packetization.Flit entries.
	"github.com/sarchlab/akita/v5/messaging"
)

func msgMetaToFlits(
	meta messaging.MsgMeta,
	spec Spec,
	networkPortRemote messaging.RemotePort,
	defaultSwitchDst messaging.RemotePort,
) []packetization.Flit {
	numFlit := 1
	if meta.TrafficBytes > 0 {
		trafficByte := meta.TrafficBytes
		trafficByte += int(math.Ceil(
			float64(trafficByte) * spec.EncodingOverhead))
		numFlit = (trafficByte-1)/spec.FlitByteSize + 1
	}

	flits := make([]packetization.Flit, numFlit)
	for i := 0; i < numFlit; i++ {
		flits[i] = packetization.Flit{
			MsgMeta: messaging.MsgMeta{
				ID:  timing.GetIDGenerator().Generate(),
				Src: networkPortRemote,
				Dst: defaultSwitchDst,
			},
			SeqID:        i,
			NumFlitInMsg: numFlit,
			Msg: messaging.MsgMeta{
				ID:           meta.ID,
				Src:          meta.Src,
				Dst:          meta.Dst,
				RspTo:        meta.RspTo,
				TrafficClass: meta.TrafficClass,
				TrafficBytes: meta.TrafficBytes,
			},
		}
	}

	return flits
}

// outgoingMW handles the device→network path:
// sendFlitOut, prepareMsg, prepareFlits.
type outgoingMW struct {
	comp             *modeling.Component[Spec, State, modeling.None]
	devicePorts      []messaging.Port
	defaultSwitchDst messaging.RemotePort
}

// networkPort resolves the endpoint's network port by name. The instance is
// assigned externally after Build, so it is resolved lazily.
func (m *outgoingMW) networkPort() messaging.Port {
	return m.comp.GetPortByName("NetworkPort")
}

// Tick runs the outgoing stages.
func (m *outgoingMW) Tick() bool {
	madeProgress := false

	madeProgress = m.sendFlitOut() || madeProgress
	madeProgress = m.prepareMsg() || madeProgress
	madeProgress = m.prepareFlits() || madeProgress

	return madeProgress
}

func (m *outgoingMW) sendFlitOut() bool {
	madeProgress := false
	spec := m.comp.Spec()
	state := &m.comp.State

	numSent := 0

	for i := 0; i < spec.NumOutputChannels; i++ {
		if numSent >= len(state.FlitsToSend) {
			break
		}

		flit := state.FlitsToSend[numSent]

		if !m.networkPort().CanSend() {
			break
		}

		m.networkPort().Send(flit)
		numSent++
		madeProgress = true
	}

	if numSent > 0 {
		state.FlitsToSend = state.FlitsToSend[numSent:]

		if len(state.FlitsToSend) == 0 {
			for _, p := range m.devicePorts {
				p.NotifyAvailable()
			}
		}
	}

	return madeProgress
}

// maxMsgOutBufSize limits the number of messages buffered before flit
// conversion. This prevents the serialisable state from growing
// unboundedly.
const maxMsgOutBufSize = 16

func (m *outgoingMW) prepareMsg() bool {
	madeProgress := false
	state := &m.comp.State

	for i := 0; i < len(m.devicePorts); i++ {
		// Backpressure: stop accepting new messages when the outgoing
		// message buffer is already large enough.
		if len(state.MsgOutBuf) >= maxMsgOutBufSize {
			break
		}

		port := m.devicePorts[i]
		if port.PeekOutgoing() == nil {
			continue
		}

		msg := port.RetrieveOutgoing()
		state.MsgOutBuf = append(state.MsgOutBuf, msg.Meta())

		madeProgress = true
	}

	return madeProgress
}

// maxFlitsToBuffer limits the number of flits held in FlitsToSend at once.
// This prevents the serialisable state from growing unboundedly.
const maxFlitsToBuffer = 64

func (m *outgoingMW) prepareFlits() bool {
	madeProgress := false
	spec := m.comp.Spec()
	state := &m.comp.State
	networkPortRemote := m.networkPort().AsRemote()

	for {
		if len(state.MsgOutBuf) == 0 {
			return madeProgress
		}

		// Apply backpressure: don't convert more messages to flits while
		// the flit send buffer is already large.
		if len(state.FlitsToSend) >= maxFlitsToBuffer {
			return madeProgress
		}

		meta := state.MsgOutBuf[0]
		state.MsgOutBuf = state.MsgOutBuf[1:]
		flits := msgMetaToFlits(meta, spec, networkPortRemote, m.defaultSwitchDst)

		state.FlitsToSend = append(state.FlitsToSend, flits...)

		// The carried message's own ID is the parent for all per-flit tasks
		// generated by this endpoint, matching the convention that a
		// message's ID is its sender-side task ID.
		for _, fs := range flits {
			m.logFlitE2ETask(fs, false, &meta, meta.ID)
		}

		madeProgress = true
	}
}

func (m *outgoingMW) logFlitE2ETask(
	fs packetization.Flit, isEnd bool, meta *messaging.MsgMeta, msgE2ETaskID uint64,
) {
	if m.comp.NumHooks() == 0 {
		return
	}

	if isEnd {
		tracing.EndTask(m.comp, tracing.TaskEnd{ID: fs.MsgMeta.ID})
		return
	}

	flit := packetization.Flit{
		MsgMeta:      fs.MsgMeta,
		SeqID:        fs.SeqID,
		NumFlitInMsg: fs.NumFlitInMsg,
		Msg:          *meta,
	}

	tracing.StartTask(m.comp, tracing.TaskStart{
		ID:       fs.MsgMeta.ID,
		ParentID: msgE2ETaskID,
		Kind:     "flit_e2e",
		What:     "flit_e2e",
		Location: m.comp.Name() + ".FlitBuf",
		Detail:   flit,
	})
}
