// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sarchlab/akita/v4/mem/dram/internal/org (interfaces: Channel)
//
// Generated by this command:
//
//	mockgen -destination mock_org_test.go -package dram -write_package_comment=false github.com/sarchlab/akita/v4/mem/dram/internal/org Channel
//

package dram

import (
	reflect "reflect"

	signal "github.com/sarchlab/akita/v4/mem/dram/internal/signal"
	gomock "go.uber.org/mock/gomock"
)

// MockChannel is a mock of Channel interface.
type MockChannel struct {
	ctrl     *gomock.Controller
	recorder *MockChannelMockRecorder
	isgomock struct{}
}

// MockChannelMockRecorder is the mock recorder for MockChannel.
type MockChannelMockRecorder struct {
	mock *MockChannel
}

// NewMockChannel creates a new mock instance.
func NewMockChannel(ctrl *gomock.Controller) *MockChannel {
	mock := &MockChannel{ctrl: ctrl}
	mock.recorder = &MockChannelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannel) EXPECT() *MockChannelMockRecorder {
	return m.recorder
}

// GetReadyCommand mocks base method.
func (m *MockChannel) GetReadyCommand(cmd *signal.Command) *signal.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReadyCommand", cmd)
	ret0, _ := ret[0].(*signal.Command)
	return ret0
}

// GetReadyCommand indicates an expected call of GetReadyCommand.
func (mr *MockChannelMockRecorder) GetReadyCommand(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReadyCommand", reflect.TypeOf((*MockChannel)(nil).GetReadyCommand), cmd)
}

// StartCommand mocks base method.
func (m *MockChannel) StartCommand(cmd *signal.Command) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartCommand", cmd)
}

// StartCommand indicates an expected call of StartCommand.
func (mr *MockChannelMockRecorder) StartCommand(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCommand", reflect.TypeOf((*MockChannel)(nil).StartCommand), cmd)
}

// Tick mocks base method.
func (m *MockChannel) Tick() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tick")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Tick indicates an expected call of Tick.
func (mr *MockChannelMockRecorder) Tick() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tick", reflect.TypeOf((*MockChannel)(nil).Tick))
}

// UpdateTiming mocks base method.
func (m *MockChannel) UpdateTiming(cmd *signal.Command) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateTiming", cmd)
}

// UpdateTiming indicates an expected call of UpdateTiming.
func (mr *MockChannelMockRecorder) UpdateTiming(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTiming", reflect.TypeOf((*MockChannel)(nil).UpdateTiming), cmd)
}
