// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sarchlab/akita/v4/mem/mem (interfaces: AddressConverter)
//
// Generated by this command:
//
//	mockgen -destination mock_mem_test.go -package dram -write_package_comment=false github.com/sarchlab/akita/v4/mem/mem AddressConverter
//

package dram

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAddressConverter is a mock of AddressConverter interface.
type MockAddressConverter struct {
	ctrl     *gomock.Controller
	recorder *MockAddressConverterMockRecorder
	isgomock struct{}
}

// MockAddressConverterMockRecorder is the mock recorder for MockAddressConverter.
type MockAddressConverterMockRecorder struct {
	mock *MockAddressConverter
}

// NewMockAddressConverter creates a new mock instance.
func NewMockAddressConverter(ctrl *gomock.Controller) *MockAddressConverter {
	mock := &MockAddressConverter{ctrl: ctrl}
	mock.recorder = &MockAddressConverterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAddressConverter) EXPECT() *MockAddressConverterMockRecorder {
	return m.recorder
}

// ConvertExternalToInternal mocks base method.
func (m *MockAddressConverter) ConvertExternalToInternal(external uint64) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvertExternalToInternal", external)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// ConvertExternalToInternal indicates an expected call of ConvertExternalToInternal.
func (mr *MockAddressConverterMockRecorder) ConvertExternalToInternal(external any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertExternalToInternal", reflect.TypeOf((*MockAddressConverter)(nil).ConvertExternalToInternal), external)
}

// ConvertInternalToExternal mocks base method.
func (m *MockAddressConverter) ConvertInternalToExternal(internal uint64) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvertInternalToExternal", internal)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// ConvertInternalToExternal indicates an expected call of ConvertInternalToExternal.
func (mr *MockAddressConverterMockRecorder) ConvertInternalToExternal(internal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertInternalToExternal", reflect.TypeOf((*MockAddressConverter)(nil).ConvertInternalToExternal), internal)
}
