// Code generated by MockGen. DO NOT EDIT.
// Source: bank.go

// Package org is a generated GoMock package.
package org

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	signal "github.com/sarchlab/akita/v4/mem/dram/internal/signal"
	hooking "github.com/sarchlab/akita/v4/sim/hooking"
)

// MockBank is a mock of Bank interface.
type MockBank struct {
	ctrl     *gomock.Controller
	recorder *MockBankMockRecorder
}

// MockBankMockRecorder is the mock recorder for MockBank.
type MockBankMockRecorder struct {
	mock *MockBank
}

// NewMockBank creates a new mock instance.
func NewMockBank(ctrl *gomock.Controller) *MockBank {
	mock := &MockBank{ctrl: ctrl}
	mock.recorder = &MockBankMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBank) EXPECT() *MockBankMockRecorder {
	return m.recorder
}

// AcceptHook mocks base method.
func (m *MockBank) AcceptHook(hook hooking.Hook) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AcceptHook", hook)
}

// AcceptHook indicates an expected call of AcceptHook.
func (mr *MockBankMockRecorder) AcceptHook(hook interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptHook", reflect.TypeOf((*MockBank)(nil).AcceptHook), hook)
}

// GetReadyCommand mocks base method.
func (m *MockBank) GetReadyCommand(cmd *signal.Command) *signal.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReadyCommand", cmd)
	ret0, _ := ret[0].(*signal.Command)
	return ret0
}

// GetReadyCommand indicates an expected call of GetReadyCommand.
func (mr *MockBankMockRecorder) GetReadyCommand(cmd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReadyCommand", reflect.TypeOf((*MockBank)(nil).GetReadyCommand), cmd)
}

// Hooks mocks base method.
func (m *MockBank) Hooks() []hooking.Hook {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hooks")
	ret0, _ := ret[0].([]hooking.Hook)
	return ret0
}

// Hooks indicates an expected call of Hooks.
func (mr *MockBankMockRecorder) Hooks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hooks", reflect.TypeOf((*MockBank)(nil).Hooks))
}

// Name mocks base method.
func (m *MockBank) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockBankMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockBank)(nil).Name))
}

// NumHooks mocks base method.
func (m *MockBank) NumHooks() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumHooks")
	ret0, _ := ret[0].(int)
	return ret0
}

// NumHooks indicates an expected call of NumHooks.
func (mr *MockBankMockRecorder) NumHooks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumHooks", reflect.TypeOf((*MockBank)(nil).NumHooks))
}

// StartCommand mocks base method.
func (m *MockBank) StartCommand(cmd *signal.Command) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartCommand", cmd)
}

// StartCommand indicates an expected call of StartCommand.
func (mr *MockBankMockRecorder) StartCommand(cmd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCommand", reflect.TypeOf((*MockBank)(nil).StartCommand), cmd)
}

// Tick mocks base method.
func (m *MockBank) Tick() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tick")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Tick indicates an expected call of Tick.
func (mr *MockBankMockRecorder) Tick() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tick", reflect.TypeOf((*MockBank)(nil).Tick))
}

// UpdateTiming mocks base method.
func (m *MockBank) UpdateTiming(cmdKind signal.CommandKind, cycleNeeded int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateTiming", cmdKind, cycleNeeded)
}

// UpdateTiming indicates an expected call of UpdateTiming.
func (mr *MockBankMockRecorder) UpdateTiming(cmdKind, cycleNeeded interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTiming", reflect.TypeOf((*MockBank)(nil).UpdateTiming), cmdKind, cycleNeeded)
}
